// <auto-generated />
using IntegrationMonitoringApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationMonitoringApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226010947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("IntegrationMonitoringApi.Controllers.IntegrationEndpoint", b =>
                {
                    b.Property<int>("IntegrationEndpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IntegrationEndpointId");

                    b.ToTable("IntegrationEndpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
